baseURL = "/"
languageCode            = "en-us"
defaultContentLanguage  = "en"
title = "Erik Parr Dev"
theme = "zozo"
summaryLength = 10000000
paginate = 1                       # shows the number of articles  # 首页显示文章数量
googleAnalytics = ""                 # your google analytics id
disqusShortname = ""                 # your discuss shortname

[author]                             # essential                     # 必需
  name = "Erik"

[blackfriday]
  smartypants = false

[[menu.main]]                        # config your menu  # 配置菜单
  name = "home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "CV"
  weight = 20
  identifier = "cv"
  url = "/cv/"
# [[menu.main]]
#   name = "tags"
#   weight = 30
#   identifier = "tags"
#   url = "/tags/"
# [[menu.main]]
#   name = "about"
#   weight = 40
#   identifier = "about"
#   url = "/about/"

[params]
  subTitle = "Creative Technology - Development and Research Studio"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "footerSlogan"                                          # site's footer slogan  # 网站页脚标语
  keywords = ["erik parr"]                                  # site's keywords  # 网站关键字
  description = "Erik Parr - Creative Dev Portfolio"                        # site's description  # 网站描述

# mathjax
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）

  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# [social]
#   github = " "
#   twitter = " "
#   facebook = " "
#   weibo = " "
#   instagram = " "
